server:
  port: 9001
spring:
  application:
    name: clientes-api
info:
  app:
    name: Clientes API
    description: API para buscar os clientes
    version: 0.1.0
eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:9000/eureka