server:
  port: 9002
spring:
  application:
    name: hoteis-api
info:
  app:
    name: Hoteis API
    description: API para buscar os hoteis
    version: 0.1.0
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9000/eureka